Repository seapath/ansible, pull requests merged in 2024-02, with the labels that each got.

#359 add_vm_playbook_example: fix path of vm_template
  examples/playbooks/add_vm_playbook_example.yaml
Labels: documentation, Yocto

#368 cluster_setup_network: make syslog optional
  examples/inventories/advanced_inventory_cluster_example.yaml
  playbooks/cluster_setup_network.yaml
Labels: enhancement, Yocto

#375 playbooks: Add a playbook to configure NICs IRQs affinity
  inventories/seapath_cluster_definition_example.yml
  inventories/seapath_standalone_definition_example.yml
  playbooks/cluster_setup_configure_nic_irq_affinity.yaml
  playbooks/tasks/setup_nic_irq_affinity.yaml
  src/setup_nic_irq_affinity.py
  src/setup_nic_irq_affinity.service
  templates/setup_nic_irq_affinity.j2
Labels: enhancement, Debian

#374 playbooks: Add a playbook to configure NICs IRQs affinity
  examples/inventories/advanced_inventory_cluster_example.yaml
  examples/inventories/advanced_inventory_standalone_example.yaml
  playbooks/cluster_setup_configure_nic_irq_affinity.yaml
  playbooks/tasks/setup_nic_irq_affinity.yaml
  src/setup_nic_irq_affinity.py
  src/setup_nic_irq_affinity.service
  templates/setup_nic_irq_affinity.j2
Labels: enhancement, Yocto

#381 ovs_configuration.json.j2: fix default option for OVS configuration
  templates/ovs_configuration.json.j2
Labels: bug, Debian

#388 github/workflows: fix ansible-lint-yocto-weekly workflow
  .github/workflows/ansible-lint-yocto-weekly.yml
Labels: bug, Yocto

#390 github/workflows: add workflow_dispatch to weekly workflows
  .github/workflows/ansible-lint-yocto-weekly.yml
  .github/workflows/ci-yocto-weekly.yml
Labels: enhancement, Yocto

#389 github/workflows: fix ansible-lint-debian-weekly workflow
  .github/workflows/ansible-lint-debian-weekly.yml
  .github/workflows/ci-debian-weekly.yml
Labels: bug, Debian

#392 github/workflows: add weekly debian CI
  .github/workflows/ansible-lint-debian-weekly.yml
  .github/workflows/ci-debian-weekly.yml
Labels: bug, Yocto, Debian

#393 github/workflows: fix Debian weekly name
  .github/workflows/ansible-lint-debian-weekly.yml
Labels: bug

#394 github/workflows: fix ci-debian-weekly fetch
  .github/workflows/ci-debian-weekly.yml
Labels: bug

#396 Update ansible-lint badge
  README.adoc
Labels: documentation
