Repository seapath/ansible, pull requests merged in 2024-07, with the labels that each got.

#531 prepare.sh: fix expansion in subshells
  prepare.sh
Labels: bug, Debian

#526 cluster_setup_ceph: fix installation on NVMe disks
  playbooks/cluster_setup_ceph_expansion.yaml
Labels: bug, Debian

#534 ci-yocto-weelly: reduce iteration loop
  .github/workflows/ci-yocto-weekly.yml
Labels: bug

#535 ansible-requirements: bump corosync-ansible version
  ansible-requirements.yaml
Labels: enhancement, Debian

#525 Dockerfile: add nodeJS package manager
  .cqfd/docker/Dockerfile
Labels: enhancement, Debian

#544 playbooks/cluster_setup_ha: run extra CRM commands on cluster_machines
  playbooks/cluster_setup_ha.yaml
Labels: bug, Yocto

#545 playbooks/tasks/deploy_vm.yaml: change default value
  playbooks/deploy_vms_cluster.yaml
  playbooks/tasks/deploy_vm.yaml
Labels: enhancement, Yocto

#547 playbooks/tasks/deploy_vm.yaml: change default value
  playbooks/deploy_vms_cluster.yaml
  playbooks/tasks/deploy_vm.yaml
Labels: enhancement, Debian

#554 fix Savoir-faire Linux copyright
  examples/inventories/advanced_inventory_cluster_example.yaml
  examples/inventories/advanced_inventory_standalone_example.yaml
  examples/inventories/netplan_admin_br0_example.yaml.j2
  examples/inventories/netplan_cluster_example.yaml.j2
  examples/inventories/netplan_ptp_interface_example.yaml.j2
  examples/inventories/vms_inventory_example.yaml
  examples/vm_templates/vm_template_example.xml.j2
  examples/vm_templates/vm_template_example_generic.xml.j2
  playbooks/cluster_setup_add_livemigration_user.yaml
  playbooks/cluster_setup_ceph.yaml
  playbooks/cluster_setup_configure_hugepages.yaml
  playbooks/cluster_setup_libvirt.yaml
  playbooks/deploy_vms_cluster.yaml
  templates/vm/vm.xml.j2
  templates/vm/vm_dpdk.xml.j2
  templates/vm/vm_dpdk_isolated.xml.j2
  templates/vm/vm_rt_dpdk.xml.j2
  templates/vm/vm_rt_isolated.xml.j2
  tests/add_vm_from_template.yaml
  tests/vm_template.xml.j2
  vars/network_vars.yml
Labels: bug, Yocto

#555 fix Savoir-faire Linux copyright
  examples/vm_templates/vm_template_example.xml.j2
  examples/vm_templates/vm_template_example_generic.xml.j2
  inventories/README.md
  inventories/netplan_admin_br0_example.yaml.j2
  inventories/netplan_cluster_example.yaml.j2
  inventories/netplan_ptp_interface_example.yaml.j2
  playbooks/cluster_setup_add_livemigration_user.yaml
  playbooks/deploy_vms_cluster.yaml
  tests/add_vm_from_template.yaml
  tests/vm_template.xml.j2
Labels: bug, Debian

#557 module_documentation_source: bump Pygments version to 2.18.0 or greater
  module_documentation_sources/requirements.txt
Labels: Debian

#556 module_documentation_source: bump Pygments version to 2.18.0 or greater
  module_documentation_sources/requirements.txt
Labels: Yocto

#560 ci_latency_tests: change pcap file location
  ci_latency_tests/.gitkeep
  ci_latency_tests/pcaps/Df_Tri_Z1.pcap
  playbooks/ci_latency_tests.yaml
Labels: enhancement, Yocto

#564 deploy_vm: fix and document ansible_remote_tmp variable
  examples/inventories/advanced_inventory_cluster_example.yaml
  playbooks/deploy_vms_standalone.yaml
  playbooks/tasks/deploy_vm.yaml
Labels: bug, Yocto

#570 bump vm_manager: add migration_downtime option
  library/cluster_vm.py
Labels: enhancement, Yocto

#571 library/cluster_vm: add new commands to add / remove Pacemaker remotes (Yocto)
  library/cluster_vm.py
Labels: enhancement, Yocto
