Repository seapath/ansible, pull requests merged in 2024-04, with the labels that each got.

#465 seapath_demo_cluster_definition: add basic template to make a cluster
  inventories/README.md
  inventories/basic_cluster.png
  inventories/seapath_demo_cluster_definition_example.yml
Labels: documentation

#453 cluster_setup_network: making cluster_ip_addr's variable optionnal
  playbooks/cluster_setup_network.yaml
Labels: enhancement, Debian

#473 seapath_demo_cluster_example: add interface to wait for at boot time
  inventories/seapath_demo_cluster_definition_example.yml
Labels: Debian

#478 ci-yocto.yml: fix VMs tests call
  .github/workflows/ci-yocto.yml
Labels: bug

#477 ptpstatus: reimplementation our own script
  src/debian/ptpstatus/ptpstatus.sh
Labels: bug
